//Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, 
//that is generated by deleting some character of a given string without changing its order.
public class SubsequenceOfString 
{
	public static void subsequence(String s,String ans)
	{
		//base case is when string becomes empty
		if(s.length()==0)
		{
			System.out.println(ans);
			return ;
		}
		//including 
		subsequence(s.substring(1),ans+s.charAt(0));
		//not including
		subsequence(s.substring(1),ans);
	}

	public static void main(String[] args) 
	{
		
		subsequence("abc","");

	}

}
